const mutationTimings = {
  'LV_Ees': 'EndDiastolic',
  'LV_alpha': 'EndSystolic',
  'LV_beta': 'EndSystolic',
  'LV_Tmax': 'EndDiastolic',
  'LV_tau': 'EndSystolic',
  'RV_Ees': 'EndDiastolic',
  'RV_alpha': 'EndSystolic',
  'RV_beta': 'EndSystolic',
  'RV_Tmax': 'EndDiastolic',
  'RV_tau': 'EndSystolic',
  'LA_Ees': 'EndDiastolic',
  'LA_alpha': 'EndSystolic',
  'LA_beta': 'EndSystolic',
  'LA_Tmax': 'EndDiastolic',
  'LA_tau': 'EndSystolic',
  'RA_Ees': 'EndDiastolic',
  'RA_alpha': 'EndSystolic',
  'RA_beta': 'EndSystolic',
  'RA_Tmax': 'EndDiastolic',
  'RA_tau': 'EndSystolic',
  'HR': 'HR',
}
export default mutationTimings